NumPy  çeşitli matematiksel işlemler yapmamızı, çok  boyutlu diziler ve matrisler üzerinde çalışmamızı sağlayan bir python kütüphanesidir. Aşağıdaki kod satırıyla koda dahil edilir.



In [ ]:
import numpy as np

# NumPy Dizisi(Array) Oluşturma

In [ ]:
dizi=np.array([2,3,5,7])

In [ ]:
dizi1=np.array([[1,1,2],
               [8,13,21],
               [42,76,118]])

In [ ]:
dizi2=np.array((1,2,3)) #Tuple ile oluşturulmuş NumPy array

In [ ]:
np.zeros((2,2)) #Sadece 0lardan oluşan 2x2 boyutunda bir dizi üretir

array([[0., 0.],
       [0., 0.]])

👇Fark edileceği üzere bu array içindekiler float değerindedir. Integer değere çevirmek için aşağıdaki kod satırı uygulanabilir. 👇

In [ ]:
np.zeros((2,2), dtype = np.int64)

array([[0, 0],
       [0, 0]])

In [ ]:
np.ones((3,3)) #Sadece 1lerden olluşan 3x3 boyutunda dizi üretir

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.random.random((5,5)) #Rastgele sayılardan oluşan 5x5lik bir dizi üretir

array([[0.95371473, 0.29926984, 0.0863122 , 0.90524503, 0.2906997 ],
       [0.14219347, 0.1693388 , 0.42844603, 0.74550543, 0.42774069],
       [0.36687317, 0.6243246 , 0.53088091, 0.65008288, 0.79063679],
       [0.70449142, 0.35725706, 0.73282972, 0.24272965, 0.99830351],
       [0.50715984, 0.89543242, 0.78856009, 0.09240374, 0.91204965]])

In [ ]:
np.random.normal(0, 1, (3, 3))

In [ ]:
np.random.randint(0, 10, (3, 3))

In [ ]:
np.empty((2,2)) #2x2lik boş bir dizi üretir

array([[3.57195233e-316, 2.47379779e-091],
       [2.44041296e-154, 2.46564255e-154]])

In [ ]:
np.full((2,2),6,dtype="int")

array([[6, 6],
       [6, 6]])

In [ ]:
# nested lists result in multi-dimensional arrays
np.array([range(i, i + 3) for i in [2, 4, 6]])

# Slicing İşlemi

In [ ]:
dizi[:2] #Baştan ikinci indeksteki elemana kadar olan kısmı yazdırır

array([2, 3])

In [ ]:
dizi[::2] #Baştan sona ikişer ikişer atlaya atlaya yazdırır

array([2, 5])

In [ ]:
dizi1[:1] #İki boyutlu dizilerde satır bazında slicing işlemi yapılır

array([[1, 1, 2]])

In [ ]:
dizi1[:,:2] 

array([[ 1,  1],
       [ 8, 13],
       [42, 76]])

İki boyutlu dizilerde şu tarz bir slicing işlemi yapılabilir ancak dikkat edilmesi gerek husus slicing işlemi yapılacak NumPy dizisinin eşit boyutlarda (örneğin 3x3 veya 4x4 lük matris) olmasıdır. Aksi halde "too many indices for array" hatası alınacaktır



# NumPy Dizilerinde Basit İşlemler

## **Matematiksel İşlemler**

In [ ]:
a=np.array([[1,2,3],
           [4,5,6],
           [7,8,9]])

In [ ]:
a.sum() #NumPy dizisi içindeki tüm elemanların toplamıdır

45

In [ ]:
b=np.array([[1,1,1],
           [1,1,1],
           [1,1,1]])

In [ ]:
a+b #İki dizinin tüm elemanlarını birbiriyle toplar

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [ ]:
a-1 #Dizideki her elemandan bir azaltır

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
np.sqrt(a) #A dizisindeki her elemanın karekökünü alır

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [ ]:
a.shape #A dizisinin boyutudur

(3, 3)

In [ ]:
a.T #A dizisinin satırlarıyla sütunlarını yer değiştirir. Bir anlamda Transpoze işlemi yapar

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

## **Basit işlemler**

In [ ]:
a.ndim #A dizisinin kaç boyutlu olduğudur

2

In [ ]:
a.dtype #A dizisindeki elemanların tip değerlerini gösterir

dtype('int64')

In [ ]:
a.astype(float) #A dizisinin elemanlarını tiplerini değiştirir

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

## **Kopyalama ve Sıralama**


In [ ]:
copy_array=np.copy(a)

In [ ]:
copy_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
d=np.array([[9,8,7],
           [6,5,4],
           [3,2,1]])

In [ ]:
d.sort()

In [ ]:
print(d)

[[7 8 9]
 [4 5 6]
 [1 2 3]]


# Liste Manipülasyonu

In [ ]:
np.append(a,-5)  #Bir diziye yeni elemanlar eklemeye yarar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, -5])

In [ ]:
np.append(a,b)  #İki diziyi birbirine eklemeye yarar

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
x=np.array([[1,1,1],
            [2,2,2],
            [3,3,3]])

In [ ]:
np.delete(x,1,axis=0)

array([[1, 1, 1],
       [3, 3, 3]])

In [ ]:
np.divide(x,a)

array([[1.        , 0.5       , 0.33333333],
       [0.5       , 0.4       , 0.33333333],
       [0.42857143, 0.375     , 0.33333333]])

In [ ]:
np.add(x,a)

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])

# Örnekler

Örnek1: Oluşturulan NumPy arrayde NaN değer olup olmadığını sorgulayan program

In [ ]:
soru1=np.array([1, 0, np.nan, 3])
print(np.isfinite(soru1))

[ True  True False  True]


Örnek2: 30'dan 70'e kadar giden bir numpy array yazın

In [ ]:
np.arange(30,71)

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69, 70])

Örnek3: 30'dan 70'e kadar tüm çift tam sayılardan oluşan bir dizi

In [ ]:
np.arange(30,71,2)

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70])

Örnek3: 3x3 lük bir birim matris oluşturunuz

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Örnek4: 15 adet rastgele sayı içeren bir array yazınız

In [ ]:
np.random.normal(0,1,15)

array([ 1.40506323, -0.3343443 ,  0.98105687,  0.0588875 ,  0.26062577,
       -1.07793241, -0.36601622,  0.5279415 , -0.91157526,  0.49348451,
        0.09106866, -3.09394266, -0.30668684,  0.69506775, -0.04312586])

Örnek5: 15 ile 55 arasındaki sayılarla bir array oluşturun. İlk ve son değerler hariç diğerlerini yazdırın

In [ ]:
soru5=np.arange(15,56)
soru5[1:-1]

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54])

Örnek6: 10dan 21e kadar olan sayıları 3x5lük bir matrise yazınız

In [ ]:
np.arange(10,22).reshape((3, 4))

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

Örnek7: Ana köşegen 1,2,3,4,5 olan bir sıfır matris oluşturunuz

***Çözüm 1***

In [ ]:
soru7=np.zeros((5,5),dtype='int')
soru7[0][0]=1
soru7[1][1]=2
soru7[2][2]=3
soru7[3][3]=4
soru7[4][4]=5
print(soru7)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [ ]:
np.diag([1, 2, 3, 4, 5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

Örnek8: Tüm elemanların toplamını, her bir sütunun toplamını ve belirli bir dizinin her satırının toplamını hesaplayınız

In [ ]:
soru8=np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
toplam=soru8.sum()
toplam_satır=soru8.sum(axis=0)
toplam_sutun=soru8.sum(axis=1)
print(toplam,toplam_satır,toplam_sutun)

45 [12 15 18] [ 6 15 24]


Örnek9: Verilen iki vektörün iç çarpımını yazan kod

In [ ]:
soru9=np.array([1,2,3])
soru9_1=np.array([9,8,7])
print(np.dot(soru9,soru9_1))

# 1*7+2*8+3*9

46


Örnek10: Bir matrisin her satırına bir vektördeki sayıları ekleyen kod

In [ ]:
soru10 = np.array([[1,2,3], 
                   [4,5,6], 
                   [7,8,9], 
                   [10, 11, 12]])
soru10_1=np.array([1, 1, 0])
empty_array=np.empty_like(soru10)

for i in range(len(soru10)):
  empty_array[i,:]=soru10[i,:]+soru10_1

print(empty_array)


[[ 2  3  3]
 [ 5  6  6]
 [ 8  9  9]
 [11 12 12]]


Örnek11: Numpy dtype'ları yerel python türlerine dönüştüren kod

In [ ]:
soru11_numpy_value=np.float32(0)
print(type(soru11_numpy_value))
soru11_python_value=soru11_numpy_value.item()
print(type(soru11_python_value))

<class 'numpy.float32'>
<class 'float'>
